contentColumnType: text
fieldGroup: ecec799f-b757-4018-941b-e2c75c877471
handle: longitude
instructions: ''
name: Longitude
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
